### ISSUE TITLE
ImportError: No module named gpu_nms

### ISSUE THREAD

**Issue by weizheliu** [liuwei16/ALFNet#12]
I'm new to detection and find this problem:

from nms.gpu_nms import gpu_nms
ImportError: No module named gpu_nms

it seems like we need to compile the cython code, I don't know how to do it, even though I write a new setup.py but it gets another error...

if I compile it from the faster-rcnn repo, I got the problem that I use gcc-7.3 while they only support the version before 6.

The  one released in another issue is only for cuda 8 while I use cuda 9, therefore, I don't know how to fix this problem.

could someone tell me how to fix this problem?

**Comment by Kyanite123** [comment]
in the $faster-rcnn/lib run make and then copy the created nms directory to the current project  (downloaded the project from https://github.com/rbgirshick/py-faster-rcnn).

Worked smoothly.

**Comment by weizheliu** [comment]
problem solved by compiling it from faster rcnn repo

**Comment by Tclz** [comment]
> in the $faster-rcnn/lib run make and then copy the created nms directory to the current project (downloaded the project from https://github.com/rbgirshick/py-faster-rcnn).
> 
> Worked smoothly.

Hi, I am using faster-rcnn with caffe，and i meet the similar problem. I have downloaded the faster-rcnn project the executed "make" in directory lib. But the generated nms directory seems did not work.  Does the Python version matter in here ? (I build and Compile Caffe with python2.7, but the command make in directory lib seems to use python3) . I am confused now. Do you have any idea to fix it? thanks in advance!!
